// define ui-action-types & export them
// LOGIN
// LOGOUT
// DISPLAY_NOTIFICATION_DRAWER
// HIDE_NOTIFICATION_DRAWER

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const DISPLAY_NOTIFICATION_DRAWER = 'DISPLAY_NOTIFICATION_DRAWER';
export const HIDE_NOTIFICATION_DRAWER = 'HIDE_NOTIFICATION_DRAWER';
